Improvements in reporting tests & CI (#483)
* Improves the CI tests for reporting (#479)

* Added reference files for better report comparison.
* Renamed cmake variables to increase readability.
* Enabled libsonata tests in reports.

diff --git a/tests/integration/reportinglib/1.check.in b/tests/integration/reportinglib/1.check.in
--- a/tests/integration/reportinglib/1.check.in
+++ b/tests/integration/reportinglib/1.check.in
@@ -1,27 +1,22 @@
-#! /bin/sh
-
-#NOTE: binary diff is not a good idea as it dont reflect what people use to read reports
+#!/bin/sh
 
 OK=0
 FAILED=1
-sonata_reports=@ENABLE_SONATA_REPORTS@
-bin_reports=@ENABLE_BIN_REPORTS@
+sonata_reports=@ENABLE_SONATA_REPORTS_TESTS@
+bin_reports=@ENABLE_BIN_REPORTS_TESTS@
+test_ref=@CMAKE_CURRENT_BINARY_DIR@/@SIM_NAME@/test_ref.out
 
 if [ "$bin_reports" = "ON" ]
 then
   if [ -f test_1.bbp ]
   then
-     #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
-     # for ascii files that will be using grep for instance.
-     nb_recorded=$(@reportinglib_somaDump@ test_1.bbp 1| wc -l)
-     # 101 because a white space
-     if [ $nb_recorded -eq 100 ]; then
-       exit $OK
-     else
-       echo "[ERROR] The number of steps recorded by ReportingLib doesn't match.
-             Found $nb_recorded, expected 100. Test failed!" >&2
-       exit $FAILED
-     fi
+    somaDump_diff=$(@reportinglib_somaDump@ test_1.bbp 1 | sed 's/ //g' | diff $test_ref -)
+    
+    if [ $? -ne 0 ]
+    then
+      echo -e "[ERROR] The report output generated by Reportinglib differs!\n$somaDump_diff" >&2
+      exit $FAILED
+    fi
   else
      echo "[ERROR] Expected ReportingLib soma file 'test_1.bbp' is missing. Test failed!" >&2
      exit $FAILED
@@ -32,19 +27,18 @@ if [ "$sonata_reports" = "ON" ]
 then
   if [ -f test_2.h5 ]
   then
-     #checking something with @reportinglib_BIN_DIR@/dump test_1.bbp
-     # for ascii files that will be using grep for instance.
-     nb_recorded_sonata=$(@H5DUMP_EXECUTABLE@ -d /report/data -y -O test_2.h5 | wc -l)
-     # 101 because a white space
-     if [ $nb_recorded_sonata -eq 101 ]; then
-       exit $OK
-     else
-       echo "[ERROR] The number of steps recorded by SONATA doesn't match.
-            Found $nb_recorded, expected 101. Test failed!" >&2
-       exit $FAILED
-     fi
+    h5dump_diff=$(@H5DUMP_EXECUTABLE@ -d /report/All/data -y -O test_2.h5 | sed '1d;$d;s/,//g;s/ //g' | diff $test_ref -)
+    
+    if [ $? -ne 0 ]
+    then
+      echo -e "[ERROR] The report output generated by Libsonata differs!\n$h5dump_diff" >&2
+      exit $FAILED
+    fi
   else
      echo "[ERROR] Expected SONATA soma file 'test_2.h5' doesn't exist. Test failed!" >&2
      exit $FAILED
   fi
 fi
+
+# If we reach this point, all tests were successful
+exit $OK
